FROM n8nio/n8n:latest

ENV N8N_PORT=$PORT
ENV N8N_PROTOCOL=https
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin123
# Use uma chave aleatória para produção
ENV N8N_ENCRYPTION_KEY=umaChaveBemSecreta123
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV N8N_HOST=${RENDER_EXTERNAL_URL}
ENV WEBHOOK_TUNNEL_URL=${RENDER_EXTERNAL_URL}

EXPOSE 5678

CMD ["n8n", "start"]
