version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=${RENDER_EXTERNAL_URL}
      - N8N_PORT=10000
      - N8N_PROTOCOL=https
      - WEBHOOK_TUNNEL_URL=${RENDER_EXTERNAL_URL}
      - NODE_ENV=production
    ports:
      - "10000:10000"
    # Render automaticamente prove um volume /data
    volumes:
      - /data
